name: Deploy on AWS
on:
  push: 
    branches: 
      - main 

jobs: 
  deploy:
    run-on: ubuntu latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        - name: Install dependencies
      run: |
        npm install

    - name: Build app (if required)
      run: |
        npm run build
    - name: Deploy to AWS
      env:
        PORT: ${{ secrets.PORT }}
        CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        ACCESS_TOKEN_EXPIRY: ${{ secrets.ACCESS_TOKEN_EXPIRY }}
        REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
        REFRESH_TOKEN_EXPIRY: ${{ secrets.REFRESH_TOKEN_EXPIRY }}
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}

  - name: Deploy to EC2
  env:
    EC2_SSH_KEY: ${{ secrets.SECRET_KEY }}
  run: |
    echo "${EC2_SSH_KEY}" | base64 --decode > ssh-key.pem
    chmod 600 ssh-key.pem
    scp -o StrictHostKeyChecking=no -i ssh-key.pem -r * ubuntu@13.60.43.249 << 'EOF'
      cd /home/ubuntu
      git pull origin main  # Pull the latest changes
      npm install
      pm2 restart all || pm2 start server.js  # Restart the app
    EOF